spring.application.name=solar-backend

spring.datasource.url=jdbc:mysql://localhost:3306/sunop
spring.datasource.username=root
spring.datasource.password=Vishal@107072
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
